# Generated by Django 2.2.9 on 2020-01-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200114_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_vi',
        ),
    ]
