# Generated by Django 2.2.9 on 2020-01-14 10:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200114_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
